openapi: 3.0.0
info:
  title: RaterApi
  version: 1.0.0
servers:
- url: /
paths:
  /api/games:
    post:
      description: Create a game by name
      operationId: authLogin
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                name:
                  example: League of legends
                  format: name
                  type: string
              required:
              - name
              type: object
        description: Pass game name
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
          description: Wrong credentials response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
          description: Wrong credentials response
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
          description: Unathourized request, you need api token
      summary: Create a game
      tags:
      - games
      x-contentType: application/json
      x-accepts: application/json
components:
  requestBodies:
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
      required: true
  schemas:
    inline_response_201:
      example:
        data: '{}'
        message: A game has been created
      properties:
        message:
          example: A game has been created
          type: string
        data:
          type: object
      type: object
    inline_object:
      properties:
        name:
          example: League of legends
          format: name
          type: string
      required:
      - name
      type: object
    inline_response_401:
      properties:
        message:
          example: Invalid or no api token, authorize with a valid api please
          type: string
      type: object
    inline_response_400:
      properties:
        message:
          example: Name is required
          type: string
      type: object

